language: node_js
sudo: false

os:
  - linux
  - osx
  - windows

node_js:
  - 7.6.0
  - 8.5.0

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn run test

after_script:
  - nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls
